---
- name: Disable PackageKit
  systemd_service:
    name: packagekit
    enabled: false
    masked: yes
    state: stopped

- name: Install packages
  zypper:
    name:
      - apache2-utils
      - automake
      - avahi-utils
      - bcc-examples
      - bcc-tools
      - bind-utils
      - bridge-utils
      - bsdtar
      - buildah
      - chrony
      - cifs-utils
      - clang
      - crane
      - criu
      - crun
      - curl
      - dejavu-fonts
      - dropbox-cli
      - e2fsprogs
      - ed
      - efitools
      - expect
      - fakeroot
      - fortune
      - gdb
      - gh
      - git
      - glab
      - glibc-devel-static
      - glibc-utils
      - gnome-extensions
      - gnome-tweaks
      - go1.26
      - ipmitool
      - jetbrains-mono-fonts
      - jq
      - keepassxc
      - libbsd-devel
      - libcap-ng-utils
      - libcap-progs
      - libcgroup-tools
      - libva-utils
      - llvm
      - lsscsi
      - lshw
      - lsof
      - ltrace
      - lynx
      - make
      - man
      - man-pages
      - mc
      - MozillaThunderbird
      - mozilla-nss-tools
      - mtr
      - nautilus-extension-sendto-blueman
      - nautilus-extension-tilix
      - ncat
      - netcat-openbsd
      - net-tools
      - nmap
      - nping
      - patch
      - pbzip2
      - pigz
      - podman
      - podman-remote
      - openssl
      - opi
      - perl-Test-PerlTidy
      - python3-devel
      - python3-virtualenv
      - rclone
      - rootlesskit
      - rpcbind
      - rpmconf
      - rsync
      - sg3_utils
      - ShellCheck
      - skopeo
      - smartmontools
      - socat
      - sqlite3
      - strace
      - subversion
      - sudo
      - switcheroo-control
      - sysfsutils
      - tcpdump
      - telnet
      - tilix
      - tmux
      - tpm2.0-tools
      - traceroute
      - transmission-gtk
      - unzip
      - vim
      - vim-plugin-bats
      - virt-firmware
      - virt-manager
      - virt-viewer
      - wget
      - wget2
      - whois
      - xfsprogs
      - xhost
      - xsel
      - yq
      - zerofree
      - zip
      - zstd
    state: present
    update_cache: true

- name: Install package patterns
  zypper:
    name:
      - container_runtime
      - devel_C_C++
      - fonts
      - laptop
      - multimedia
    type: pattern
    state: present

- name: Uninstall packages
  zypper:
    name:
      - cups
      - cups-client
      - cups-filters
      - emacs
      - gimp
      - libreoffice
      - mcelog
      - os-prober
      - postfix
    clean_deps: true
    state: absent
